//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VBCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_HocSinh
    {
        public int ID { get; set; }
        public string MaTruong { get; set; }
        public string NamHoc { get; set; }
        public string HoChuLot { get; set; }
        public string Ten { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NamSinh { get; set; }
        public string DanToc { get; set; }
        public string NoiSinh { get; set; }
        public string DienUT { get; set; }
        public string DienKK { get; set; }
        public string Toan { get; set; }
        public string Ly { get; set; }
        public string Hoa { get; set; }
        public string Sinh { get; set; }
        public string NguVan { get; set; }
        public string Su { get; set; }
        public string Dia { get; set; }
        public string TiengAnh { get; set; }
        public string GDCD { get; set; }
        public string CongNghe { get; set; }
        public string TiengPhap { get; set; }
        public string TheDuc { get; set; }
        public string Nhac { get; set; }
        public string MyThuat { get; set; }
        public string TBCN { get; set; }
        public string XepLoaiHL { get; set; }
        public string XepLoaiHK { get; set; }
        public string XepLoaiTN { get; set; }
        public string Lop { get; set; }
        public Nullable<int> BuoiNghi { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string Ngay { get; set; }
        public string Thang { get; set; }
        public string Nam { get; set; }
    }
}
