//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VBCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NhanVien_DaoTao
    {
        public int ID { get; set; }
        public string MaNhanVien { get; set; }
        public string TrangThai { get; set; }
        public string NgayBatDau { get; set; }
        public string NgayKetThuc { get; set; }
        public string TrinhDo { get; set; }
        public string HinhThuc { get; set; }
        public string TenTruong { get; set; }
        public string ChuyenNganh { get; set; }
        public string NuocDaoTao { get; set; }
        public string KhoaDaoTao { get; set; }
        public string ChuongTrinhDaoTao { get; set; }
        public Nullable<bool> CuDiHoc { get; set; }
        public string NguonKinhPhi { get; set; }
        public string TotNghiepLoai { get; set; }
        public string SoVanBang { get; set; }
        public Nullable<System.DateTime> NgayVanBang { get; set; }
        public Nullable<int> IDDaoTao { get; set; }
        public string LinkFile { get; set; }
        public string Extension { get; set; }
    }
}
