//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VBCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_SoGocVanBang_ChiTiet
    {
        public int ID { get; set; }
        public string MaDonVi { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NamSinh { get; set; }
        public string NoiSinh { get; set; }
        public string GioiTinh { get; set; }
        public string DanToc { get; set; }
        public string XepLoaiTotNghiep { get; set; }
        public string SoHieuVanBang { get; set; }
        public string SoVaoSoGoc { get; set; }
        public string GhiChu { get; set; }
    }
}
