//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VBCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_SoGocVanBang
    {
        public int ID { get; set; }
        public string MaDonVi { get; set; }
        public string So { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<int> MaTruong { get; set; }
        public Nullable<int> NamHoc { get; set; }
        public Nullable<int> HinhThuc { get; set; }
        public Nullable<System.DateTime> NgayKy { get; set; }
    }
}
