//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VBCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Truong
    {
        public int ID { get; set; }
        public string MaDonVi { get; set; }
        public string TenTruong { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string HieuTruong { get; set; }
        public string CapHoc { get; set; }
    }
}
