//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VBCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UMS_MenuGroupUser
    {
        public string Id { get; set; }
        public string MenuId { get; set; }
        public string GroupUserId { get; set; }
        public Nullable<int> CanEdit { get; set; }
    }
}
